### PR TITLE
Fix docker ci

### PR DESCRIPTION
**Pull request by danjampro**
- Fixes broken docker CI by upgrading buildx action version (tested via GHA).
- Updates badges in readme.
- Renames actions for nicer badges.

### CODE REVIEW

**Review by wtgee — APPROVED** [review]
:+1: 

Do we know what changed between the v1 and v3 of the buildx helper that makes this work?

**Comment by wtgee** [comment]
Only other comment is that we have an inconsistency with `yml` vs `yaml`. Not a huge deal but should probably make them consistent.

**Comment by danjampro** [comment]
> 👍
> 
> Do we know what changed between the v1 and v3 of the buildx helper that makes this work?

To be honest, no. It was just a hunch I had given that it would successfully build locally with buildx.

**Comment by danjampro** [comment]
> Only other comment is that we have an inconsistency with `yml` vs `yaml`. Not a huge deal but should probably make them consistent.

Good point. I've read that `.yml` is preferable over `.yaml`, but I'm not sure whether that would interfere with the way `pocs` is setup.

**Pull request merged**
