### PR TITLE
Removing dithering - DO NOT MERGE

### PR DESCRIPTION
**Pull request by wtgee**
Dithering utils have been merged upstream.

Dependent on https://github.com/panoptes/POCS/pull/735

### CODE REVIEW

**Review by lspitler — APPROVED** [review]

**Review by bazkiaei — APPROVED** [review]

**Review by AnthonyHorton — APPROVED** [review]
All good, once the upstream PR has been merged.

**Comment by wtgee** [comment]
Triple approval! :)

**Comment by bazkiaei** [comment]
> Triple approval! :)

This was the first time I approved a PR I think. :dancer:

**Comment by wtgee** [comment]
Closing as this no longer appears relevant and generic dithering should be upstream at POCS.

**Pull request closed without merging**
