### PR TITLE
Fix exposure

### PR DESCRIPTION
**Pull request by danjampro**
Quick fix for the (currently failing) test_exposure:

- Overrides is_ready in pyro.camera

- Checks is_exposing before any thing else in is_ready. This allows is_ready to behave as expected when an exposure is already in progress by bypassing the rest of the check. 

- For some reason, the other checks seemed to cause the is_ready method to wait until the exposure was completed previously. I do not have a clear idea about why this is, but is_temperature_stable may be the culprit...

### CODE REVIEW

**Review by fergusL — APPROVED** [review]
I'm not familiar with the camera control code but LGTM

**Review by wtgee — APPROVED** [review]
LGTM although I would say to add some logging. Here we would just find out that camera is not ready but wouldn't know why. Some `debug` statements before each possible `return` might be helpful.

**Comment by danjampro** [comment]
> LGTM although I would say to add some logging. Here we would just find out that camera is not ready but wouldn't know why. Some `debug` statements before each possible `return` might be helpful.

Done.

**Comment by AnthonyHorton** [comment]
Very late to the party here, but it's bugging me that we have to duplicate so much `is_ready` code here. I think this is mostly a consequence of the decision to make the `take_exposure` method of the `CameraServer` be blocking, otherwise you'd just pass the `is_ready` call through to the remote camera.

**Pull request merged**
